//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Note_Marketplace.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerNotesReportedIssue
    {
        public int ID { get; set; }
        public int NOTEID { get; set; }
        public int ReportedBYID { get; set; }
        public int AgainstDownloadID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
